In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Characters.csv", sep=";")
df

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
0,1,Harry James Potter,Male,Student,Gryffindor,"11"" Holly phoenix feather",Stag,Human,Half-blood,Black,Bright green,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,"12"" Ash unicorn tail hair",Jack Russell terrier,Human,Pure-blood,Red,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,"10¾"" vine wood dragon heartstring",Otter,Human,Muggle-born,Brown,Brown,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,"15"" Elder Thestral tail hair core",Phoenix,Human,Half-blood,Silver| formerly auburn,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,"16"" Oak unknown core",NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Black,Black,Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,136,Wilhelmina Grubbly-Plank,Female,Substitute professor of Care of Magical Creatu...,NaN,Unknown,Non-corporeal,Human,NaN,Grey,NaN,Hogwarts School of Witchcraft and Wizardry,NaN,NaN,NaN
136,137,Fenrir Greyback,Male,NaN,NaN,Unknown,NaN,Werewolf,NaN,Grey,NaN,Lord Voldemort | Death Eaters,Physical combat,Pre 1945,NaN
137,138,Gellert Grindelwald,Male,Revolutionary leader(c. 1920s[6] – 1945),NaN,"15"", Elder, Thestral tail hair core",NaN,Human,Pure-blood or half-blood,Blond,Blue,Gellert Grindelwald's Acolytes,Duelling,1883,"March, 1998"
138,139,Dobby,Male,"Malfoy family's house-elf (? - 1993),\nHogwart...",NaN,NaN,NaN,House elf,NaN,Green,NaN,NaN,"A type of magic specific to house-elves, perfo...",28 June,"Late March, 1998"
139,140,Kreacher,Male,"\nBlack family's house-elf (?-1996), \nHarry P...",NaN,NaN,NaN,House elf,NaN,White,NaN,NaN,Magic performed without a wand which includes ...,NaN,NaN

In [5]:
#Q2
df.head()

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
0,1,Harry James Potter,Male,Student,Gryffindor,"11"" Holly phoenix feather",Stag,Human,Half-blood,Black,Bright green,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,"12"" Ash unicorn tail hair",Jack Russell terrier,Human,Pure-blood,Red,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,"10¾"" vine wood dragon heartstring",Otter,Human,Muggle-born,Brown,Brown,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,"15"" Elder Thestral tail hair core",Phoenix,Human,Half-blood,Silver| formerly auburn,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,"16"" Oak unknown core",NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Black,Black,Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN

In [6]:
df.tail()

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
135,136,Wilhelmina Grubbly-Plank,Female,Substitute professor of Care of Magical Creatu...,NaN,Unknown,Non-corporeal,Human,NaN,Grey,NaN,Hogwarts School of Witchcraft and Wizardry,NaN,NaN,NaN
136,137,Fenrir Greyback,Male,NaN,NaN,Unknown,NaN,Werewolf,NaN,Grey,NaN,Lord Voldemort | Death Eaters,Physical combat,Pre 1945,NaN
137,138,Gellert Grindelwald,Male,Revolutionary leader(c. 1920s[6] – 1945),NaN,"15"", Elder, Thestral tail hair core",NaN,Human,Pure-blood or half-blood,Blond,Blue,Gellert Grindelwald's Acolytes,Duelling,1883,"March, 1998"
138,139,Dobby,Male,"Malfoy family's house-elf (? - 1993),\nHogwart...",NaN,NaN,NaN,House elf,NaN,Green,NaN,NaN,"A type of magic specific to house-elves, perfo...",28 June,"Late March, 1998"
139,140,Kreacher,Male,"\nBlack family's house-elf (?-1996), \nHarry P...",NaN,NaN,NaN,House elf,NaN,White,NaN,NaN,Magic performed without a wand which includes ...,NaN,NaN

In [7]:
df.shape

(140, 15)

In [8]:
df.columns

Index(['Id', 'Name', 'Gender', 'Job', 'House', 'Wand', 'Patronus', 'Species',
       'Blood status', 'Hair colour', 'Eye colour', 'Loyalty', 'Skills',
       'Birth', 'Death'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            140 non-null    int64
 1   Name          140 non-null    str
 2   Gender        139 non-null    str
 3   Job           121 non-null    str
 4   House         101 non-null    str
 5   Wand          132 non-null    str
 6   Patronus      123 non-null    str
 7   Species       140 non-null    str
 8   Blood status  123 non-null    str
 9   Hair colour   123 non-null    str
 10  Eye colour    86 non-null     str
 11  Loyalty       89 non-null     str
 12  Skills        113 non-null    str
 13  Birth         127 non-null    str
 14  Death         42 non-null     str
dtypes: int64(1), str(14)
memory usage: 16.5 KB

In [10]:
df.describe()

             Id
count  140.0000
mean    70.5000
std     40.5586
min      1.0000
25%     35.7500
50%     70.5000
75%    105.2500
max    140.0000

In [11]:
df.dtypes

Id              int64
Name              str
Gender            str
Job               str
House             str
Wand              str
Patronus          str
Species           str
Blood status      str
Hair colour       str
Eye colour        str
Loyalty           str
Skills            str
Birth             str
Death             str
dtype: object

In [12]:
df.isnull().sum()

Id               0
Name             0
Gender           1
Job             19
House           39
Wand             8
Patronus        17
Species          0
Blood status    17
Hair colour     17
Eye colour      54
Loyalty         51
Skills          27
Birth           13
Death           98
dtype: int64

In [13]:
df.nunique()

Id              140
Name            140
Gender            2
Job              65
House             6
Wand             29
Patronus         19
Species          10
Blood status     15
Hair colour      36
Eye colour       25
Loyalty          19
Skills           94
Birth           112
Death            25
dtype: int64

In [14]:
df.sample(5)

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
32,33,Quirinus Quirrell,Male,Defence Against the Dark Arts(1991-1992),Ravenclaw,"9"" Alder unicorn hair bendy",Non-corporeal,Human,Half-blood,NaN,NaN,Lord Voldemort,Learned in the theory of Defensive Magic| less...,"26 September,1970 or earlier",4 June 1992
50,51,Dolores Jane Umbridge,Female,Professor of Defence Against the Dark Arts | D...,Slytherin,"8"" Birch dragon heartstring",Cat,Human,Half-blood,Iron grey,NaN,Ministry of Magic,Her punishment quill is of her own invention,26 August,NaN
76,77,Amycus Carrow,Male,Professor of Dark Arts,Slytherin,Unknown,Unknown,Human,Pure-blood or half-blood,NaN,NaN,Lord Voldemort | Death Eaters,Cruciatus Curse,Pre 1982,NaN
73,74,Charity Burbage,Female,Professor of Muggle Studies,NaN,Unknown,Non-corporeal,Human,Pure-blood or half-blood,Blonde,NaN,NaN,Teaching and studying the Muggle world,Before 1976,"Late July, 1997"
116,117,Madame Olympe Maxime,Female,Headmistress of Beauxbatons Academy of Magic,Beauxbatons Academy of Magic,Unknown,Unknown,Half-Human/Half-Giant,Part-Human (Half-giant),Brown,Black,NaN,"An ‘excellent dancer’, in the words of Dumbled...",NaN,NaN

In [15]:
df["House"].value_counts()

House
Gryffindor                      38
Slytherin                       28
Ravenclaw                       18
Hufflepuff                      13
Beauxbatons Academy of Magic     3
Durmstrang Institute             1
Name: count, dtype: int64